### PR TITLE
Patch issue43 has zero point

### PR DESCRIPTION
**Pull request by GeorgFerdinandSchneider**
Revision according to discussion in #43 and #41 

Comments now indicate that property is unstable (also in vs:status)

### CODE REVIEW

**Comment by GeorgFerdinandSchneider** [comment]
if merged should close #41

**Comment by maximelefrancois86** [comment]
ok, please update the html too.

**Comment by GeorgFerdinandSchneider** [comment]
Needs small update because of typo

Links a bot:Site to an instance that encodes the latitude and longitude of the Zero Point of the building site. This could be an instance of a wgs84:Point. The definition of GIS and geometry is not within the scope of BOT and an appropriate ontology needs to be selected here by the user. The use of this property is potentially ambiguous and it might be removed or revised in future editions of the ontology.

**Comment by GeorgFerdinandSchneider** [comment]
corrected and updated html docs

**Pull request merged**
