### PR TITLE
Changed alignments of S4BLDG and BRICK according to comments by

### PR DESCRIPTION
**Pull request by GeorgFerdinandSchneider**
According to the [comments ](https://github.com/w3c-lbd-cg/bot/pull/19#issuecomment-355972323) by @MadsHolten and @mariapoveda some adjustments in the defined alignments.

### CODE REVIEW

**Review by MadsHolten — COMMENTED** [review]
Aren't both bot:containsElement and bot:containsZone subclasses of saref4bldg:contains rather than the other way around since these are more specific?

**Comment by GeorgFerdinandSchneider** [comment]
There has been some updates, the latest alignments which I would like to propose.

Please check the latest [commit](https://github.com/w3c-lbd-cg/bot/commit/2bbb5f0dbfc78bce3cef8912570cb3348f8e9ee4) to the revisingAlignments branch.

> https://github.com/w3c-lbd-cg/bot/tree/revisingAlignments

**Comment by GeorgFerdinandSchneider** [comment]
Please consider revised alignments in 

    https://github.com/w3c-lbd-cg/bot/tree/AlignmentRevision

This pull request and branch will be merged with the above branch

**Comment by GeorgFerdinandSchneider** [comment]
Hi all!

in preparation to the git issue sprint I closed this pull request as it is outdated.

The most recent alignments can be found in 

https://github.com/w3c-lbd-cg/bot/tree/AlignmentRevision

**Pull request closed without merging**
