### PR TITLE
Updated and pretty printed bot ontology

### PR DESCRIPTION
**Pull request by maximelefrancois86**
now corresponds to latest editor draft 

https://w3c-lbd-cg.github.io/lbd/bot/#changes

### CODE REVIEW

**Comment by MadsHolten** [comment]
We have to work on the bot:Zone definition. "A defined area with spatial 3D volume that groups spaces". A space is a zone itself. A zone can also be subdivision of a space.

**Comment by mathib** [comment]
What do you think of: "A defined spatial 3D volume that can represent a site, a building, a storey or a space. It can also be used to group other zones, or to define subdivisions of zones"?

**Comment by MadsHolten** [comment]
How about "A defined spatial 3D volume that can represent a site, a building, a storey or a space or any other spatial feature of interest. A zone can contain sub zones making it possible to do grouping or subdivision of existing zones."

**Comment by maximelefrancois86** [comment]
Hi, we should move this discussion to #17 and reopen it, or a new issue.  This PR has been merged

**Comment by pipauwel** [comment]
Moved to [ #17](https://github.com/w3c-lbd-cg/bot/issues/17)

**Comment by stickxxx** [comment]
Why not use the ISO definition for "zone" - ISO 18523-2:2018(en), 3.1.3 defines it as
"part of a building consisting of (part of) one or more spaces with assumed uniform properties related to a specific service or service component, or (in absence of a service) assumed uniform indoor environmental conditions"

**Pull request merged**
