### PR TITLE
Update bot.ttl

### PR DESCRIPTION
**Pull request by RichardPinka**
czech (cz) and slovak (sk) languages translations of  labels and comments of classes/d.props/o.props

### CODE REVIEW

**Comment by RichardPinka** [comment]
Hello, my goal was to update BOT by personal pull-request .. which is my first hopefully successfull try to pull request of some github code editing... which I assume it was not possible by other way just than:
create branch
create pull request within it
...and
if succes, 
then 
[...champagne hisses after is bottle opened ... ]

**Comment by GeorgFerdinandSchneider** [comment]
great thanks for submitting this request

@maximelefrancois86 @MadsHolten : I am not sure how to merge this best. The edits have been made outside of the file using an ontology editor (with owl api)

Potentially the definitions can be merged when adding other multilanguage labels as of #64

**Comment by GeorgFerdinandSchneider** [comment]
@rickiricki Could you please explain why you provide two labels each for bot:Storey?

**Comment by RichardPinka** [comment]
@GeorgFerdinandSchneider 
Option of defining two not similar terms brought to me small confusion and hesitation to select only one of the terms , to select which one suits to term "storey".
Maybe You already sorted this thing out via Your answer at LBD email discussion on this topic on 19.03.2020 .  So I will be happy to let You to decide with me. .. it is the matter of conventions which I am not sure I know

If by term "storey" may be called also an underground floor (or basement, if you want) 
than for sure it will be only one label : podlaží.     Other terms, (poschodí:CZ , poschodie:SK) has explicit meaning that are stories "above ground, never below" . 

if the sentence:  
Building has 21 floors , one ground floor and 3 basements.
                     is equal to sentence: 
Building has 25 storeys  ... than yes,  
storey shall have only label podlaží@cz  podlažie@sk.  

As you may see in picture below, as far I learned from practice (where no term "storey" was used) concrete terms used in our language (in connection with one branch of english terms)
image
interesting differentiation of conventions description is at:
https://en.wikipedia.org/wiki/Storey

actually term "level" i would likely not use in meaning of "storey" at all, because it steals you afterward possibilty to define information like this: 

"2nd floor of object A has level height 3200 mm above zero and 2nd floor of object C and D has level height just 3050 mm above zero."


regarding to my pull request :  I am not sure if that was the correct way, if not, I do not understand why. My assumption was only : I can (anybody can) do pull request in any repository.. but this is not baybe true.

**Comment by GeorgFerdinandSchneider** [comment]
Hi Richard!

as discussed in #66 the definition of storey is intended to cover also storeys below ground.

If possible you can commit to your branch to update to only one label per language.

your PR was just perfect. I suppose the problem is more on the side of bot as the current file is managed manually but should in a ontology editing tool. Potentially we can shift to something "generative" such as the BRICK tool chain.

Best

Georg

**Comment by RichardPinka** [comment]
Hello Georg, 
allrig than, as for now,  only my CZ+SK content in the google spreadsheet is valid (with bit of more modifications in other descriptions) and as was agreed by @MadsHolten , is ok to update data only throug spreadsheet. 
If You would like me to do the pull request with actual cz+sk translations, give me echo, that would not be problem for me. 

regarding to my proposal to use protégé plutin for importing from excel spreadsheets https://github.com/protegeproject/mapping-master
for data input automation into ongology : as I found out today to try create some prototype of it, 
it is not unfortunatelly possible because:  
- You cannot add language labels to string aligment to rdfs:label 
- it is not even possible to create string alignments to rdfs:comment  at all. 



best regards

**Comment by GeorgFerdinandSchneider** [comment]
This is handled in #73 

@RichardPinka please provide your translations in https://docs.google.com/spreadsheets/d/1J5mEyblGU0M57XNpwQWxHbGlilRMzmCEqoU5FmOHILE/edit#gid=0

These will  be merged then in the single PR #73. Thank you for your effort.

**Pull request closed without merging**
